FROM debian:latest
LABEL maintainer="Mark Howison <mhowison@brown.edu>"
LABEL repository="browndatascience"
LABEL image="georeg"
LABEL version="0.0.1"

RUN apt-get update
RUN apt-get install -y \
  build-essential \
  cmake \
  libeigen3-dev \
  libjpeg-dev \
  libpng-dev \
  libtesseract-dev \
  pybind11-dev \
  python-geopy \
  python-levenshtein \
  python-nltk \
  python-numpy \
  python-pip \
  python-pybind11 \
  python-sklearn-lib \
  wget \
  zlib1g-dev

RUN cd /tmp && \
  wget https://github.com/opencv/opencv/archive/3.1.0.tar.gz && \
  tar xf 3.1.0.tar.gz && \
  cd opencv-* && \
  mkdir build && \
  cd build && \
  cmake .. && \
  make && \
  make install

RUN cd /tmp && \
  wget https://github.com/brown-data-science/tessapi/archive/v0.0.1.tar.gz && \
  tar xf v0.0.1.tar.gz && \
  rm v0.0.1.tar.gz && \
  cd tessapi-* && \
  python setup.py install

RUN cd /tmp && \
  wget https://github.com/brown-data-science/georeg/archive/v0.0.1.tar.gz \
  tar xf v0.0.1.tar.gz && \
  rm v0.0.1.tar.gz && \
  cd georeg-* && \
  python setup.py install

RUN apt-get remove -y \
  build-essential \
  libeigen3-dev \
  libjpeg-dev \
  libpng-dev \
  libtesseract-dev \
  pybind11-dev \
  wget \
  zlib1g-dev
RUN apt-get autoremove
RUN rm -rf /tmp/*

ENTRYPOINT ["/usr/local/bin/georeg"]
